-- module_feat_coll.lua — Simple UI
-- Module: Featured Collection (dynamic instances).
--
-- Same presentation as TBR/Recent/New Books (horizontal row
-- of up to 5 covers — engine shared in sui_book_grid.lua), but each instance
-- is linked to ANY collection that exists in ReadCollection, chosen
-- by the user — not just "To Be Read".
--
-- Difference from module_collections.lua: that one is a grid with up to 5
-- different collections at once (1 cover per collection). This module is
-- the opposite: 1 collection, several covers — and, like Quick Actions Row,
-- you can have N instances on your homescreen (one per collection you want
-- to feature).
--
-- Exposes M.instanciable = true and M.makeInstance(id) for the registry.
-- Instances persist in "simpleui_coll_row_instances" (M.instances_key).
--
-- IMPORTANT NOTE (moduleregistry / sui_settings_window):
-- the base id deliberately ends in "_row" — Registry.createInstance generates
-- ids like "coll_row_a1b2c3", which contain the substring "_row_" used in
-- sui_settings_window.lua to distinguish instances from singleton modules.
-- See the note in moduleregistry.lua if this pattern is ever changed.

local _  = require("infra/sui_i18n").translate

local CenterContainer = require("ui/widget/container/centercontainer")
local Font            = require("ui/font")
local Geom            = require("ui/geometry")

local SUISettings = require("infra/sui_store")
local SUIStyle    = require("features/sui_style")
local UI          = require("infra/sui_core")
local GridRenderer = require("engines/sui_book_grid")

local PAD = UI.PAD

local MAX_ITEMS = 5

-- ---------------------------------------------------------------------------
-- ReadCollection accessor (lazy, same pattern as module_tbr.lua)
-- ---------------------------------------------------------------------------
local function getRC()
    local ok, rc = pcall(require, "readcollection")
    return ok and rc or nil
end

-- Name of the TBR collection (module_tbr.lua) — excluded from this module's
-- collection picker, since TBR already has its own dedicated instance/module and
-- it wouldn't make sense to be selectable here too.
local function getTBRCollName()
    local ok, TBR = pcall(require, "modules/module_tbr")
    return ok and TBR and TBR.TBR_COLL_NAME or nil
end

-- ---------------------------------------------------------------------------
-- Instance factory
-- ---------------------------------------------------------------------------
local function makeInstance(inst_id)
    local COLL_KEY = inst_id .. "_coll_name"

    local function getCollName(pfx)
        return SUISettings:readSetting(pfx .. COLL_KEY)
    end
    local function setCollName(pfx, name)
        SUISettings:saveSetting(pfx .. COLL_KEY, name)
    end

    -- Last sort mode applied via the "Sort" menu below. Unlike
    -- module_library.lua/module_collections.lua, sorting a collection is a
    -- one-shot action (it rewrites ReadCollection's order, which the user
    -- can then hand-tweak via "Arrange" on top of), not a live filter — so
    -- this key exists purely to remember what was last picked, for display
    -- (mandatory_func) on the "Sort" row. It intentionally has no effect on
    -- getFileList/GridRenderer.getCollectionFileList.
    local SORT_KEY = inst_id .. "_sort_mode"
    local function getLastSortMode(pfx)
        return SUISettings:readSetting(pfx .. SORT_KEY)
    end
    local function saveLastSortMode(pfx, mode)
        SUISettings:saveSetting(pfx .. SORT_KEY, mode)
    end

    -- Name to show when the target collection no longer exists (deleted outside
    -- SimpleUI) or hasn't been chosen yet.
    local function displayName(pfx)
        local name = getCollName(pfx)
        if not name then return _("Featured Collection — tap to configure") end
        local RC = getRC()
        if RC then
            -- Not calling RC:_read() — it destructively reloads rc.coll from
            -- disk and can wipe an in-memory-only collection the native
            -- Collections UI hasn't flushed to disk yet. The singleton is
            -- already live in-process.
            if not (RC.coll and RC.coll[name]) then
                return name .. "  " .. _("(collection not found)")
            end
        end
        return name
    end

    local function getFileList(pfx)
        local name = getCollName(pfx)
        if not name then return {} end
        return GridRenderer.getCollectionFileList(name)
    end

    -- ── Featured Collection-specific menu items: collection picker,
    --    Sort and Arrange. Prepended to the generic items (Scale/Frame/...)
    --    generated by makeModule. ──────────────────────────────────────────
    local function extraMenuItemsBefore(ctx_menu)
        local _lc         = ctx_menu._
        local refresh      = ctx_menu.refresh
        local pfx          = ctx_menu.pfx
        local SortWidget   = ctx_menu.SortWidget
        local _UIManager   = ctx_menu.UIManager
        local items = {}

        -- Choosing the target collection (single-select, radio). Implemented as
        -- sub_item_table_func (not item_picker) because it works
        -- identically in KOReader's native menu and in SUIWindow, without
        -- depending on a nested navigation context (push/pop).
        items[#items + 1] = {
            text_func = function()
                local name = getCollName(pfx)
                return name and (_lc("Collection: ") .. name) or _lc("Collection: (none)")
            end,
            separator = true,
            sub_item_table_func = function()
                local tbr_name = getTBRCollName()
                local exclude  = tbr_name and { [tbr_name] = true } or nil
                local all = GridRenderer.listAllCollectionNames(exclude)
                local sub = {}
                if #all == 0 then
                    sub[#sub + 1] = { text = _lc("No collections found."), enabled = false }
                    return sub
                end
                for _, name in ipairs(all) do
                    local _n = name
                    sub[#sub + 1] = {
                        text           = _n,
                        radio          = true,
                        checked_func   = function() return getCollName(pfx) == _n end,
                        keep_menu_open = true,
                        callback       = function()
                            setCollName(pfx, _n)
                            refresh()
                        end,
                    }
                end
                return sub
            end,
        }

        -- Sort (one-click action — rewrites the persisted order; manual
        -- Arrange remains available on top of the result). The action
        -- itself stays one-shot (picking "Title (A–Z)" again re-sorts even
        -- if it was already selected — the list may have changed since),
        -- but each option is a radio row so the last-applied mode is
        -- remembered (getLastSortMode) and shown as a checkmark in the
        -- sub-menu. The parent row's title never changes — the mode is
        -- surfaced only via mandatory_func (native Menu's right-side value)
        -- / SUIWindow's automatic right_value inference from the checked
        -- radio child (see the "Row title vs. right-side value" note in
        -- engines/sui_window.lua's SUIWindow.MenuTable doc block).
        local SORT_LABELS = {
            title_asc    = _lc("Title (A–Z)"),
            title_desc   = _lc("Title (Z–A)"),
            author_asc   = _lc("Author (A–Z)"),
            percent_asc  = _lc("% Read (ascending)"),
            percent_desc = _lc("% Read (descending)"),
            shuffle      = _lc("Shuffle"),
        }
        local SORT_ORDER = { "title_asc", "title_desc", "author_asc", "percent_asc", "percent_desc", "shuffle" }
        items[#items + 1] = {
            text_func = function() return _lc("Sort") end,
            mandatory_func = function() return SORT_LABELS[getLastSortMode(pfx)] or "" end,
            enabled_func = function() return #getFileList(pfx) > 1 end,
            sub_item_table_func = function()
                local name = getCollName(pfx)
                local sub = {}
                for _, mode in ipairs(SORT_ORDER) do
                    local _m = mode
                    sub[#sub + 1] = {
                        text           = SORT_LABELS[_m],
                        radio          = true,
                        separator      = (_m == "shuffle") or nil,
                        checked_func   = function() return getLastSortMode(pfx) == _m end,
                        keep_menu_open = true,
                        callback       = function()
                            if name then
                                GridRenderer.sortCollection(name, _m)
                                saveLastSortMode(pfx, _m)
                                refresh()
                            end
                        end,
                    }
                end
                return sub
            end,
        }

        -- Arrange (reorder the chosen collection).
        items[#items + 1] = {
            text = _lc("Arrange"),
            enabled_func = function() return getCollName(pfx) ~= nil end,
            sub_item_table_func = function()
                local sub_items = {}
                local name = getCollName(pfx)
                local list = getFileList(pfx)

                sub_items[#sub_items + 1] = {
                    text         = _lc("Arrange Collection"),
                    enabled_func = function() return #list > 1 end,
                    keep_menu_open = true,
                    callback = function()
                        if #list < 2 then
                            UI.Notify.toast(_lc("Add at least 2 books to arrange."), 2)
                            return
                        end
                        local sort_items = {}
                        for _, fp in ipairs(list) do
                            sort_items[#sort_items + 1] = {
                                text      = GridRenderer.getBookTitle(fp),
                                filepath  = fp,
                                mandatory = "",
                            }
                        end
                        local function on_save()
                            local new_list = {}
                            for _, item in ipairs(sort_items) do
                                if item.filepath then new_list[#new_list + 1] = item.filepath end
                            end
                            local RC = getRC()
                            if RC and RC.coll[name] then
                                local ordered = {}
                                for _, fp in ipairs(new_list) do
                                    local entry = RC.coll[name][fp]
                                    if entry then ordered[#ordered + 1] = entry end
                                end
                                RC:updateCollectionOrder(name, ordered)
                                RC:write({ [name] = true })
                            end
                            refresh()
                        end
                        _UIManager:show(SortWidget:new{
                            title = _lc("Arrange Collection"),
                            item_table = sort_items,
                            covers_fullscreen = true,
                            callback = on_save,
                        })
                    end,
                }

                sub_items[#sub_items + 1] = { text = _lc("Books"), enabled = false, separator = true }

                if #list == 0 then
                    sub_items[#sub_items + 1] = { text = _lc("No books in this collection."), enabled = false }
                else
                    for _, fp in ipairs(list) do
                        local _fp    = fp
                        local _title = GridRenderer.getBookTitle(fp)
                        sub_items[#sub_items + 1] = {
                            text           = _title,
                            keep_menu_open = true,
                            callback       = function()
                                local RC = getRC()
                                if RC then RC:removeItem(_fp, name) end
                                refresh()
                            end,
                        }
                    end
                end
                return sub_items
            end,
            sui_build = ctx_menu.is_sui and function(ctx, _item)
                local SUIWindow = require("engines/sui_window")
                return SUIWindow.ListRow{
                    title        = _lc("Arrange"),
                    subtitle     = function()
                        local list = getFileList(pfx)
                        if #list == 0 then return _lc("No books in this collection.") end
                        local names = {}
                        for _, fp in ipairs(list) do names[#names + 1] = GridRenderer.getBookTitle(fp) end
                        return table.concat(names, "  ·  ")
                    end,
                    inner_w      = ctx.inner_w,
                    show_chevron = true,
                    enabled      = getCollName(pfx) ~= nil,
                    on_tap       = function()
                        local name = getCollName(pfx)
                        local list = getFileList(pfx)
                        local sort_items = {}
                        for _, fp in ipairs(list) do
                            sort_items[#sort_items + 1] = { text = GridRenderer.getBookTitle(fp), orig_item = fp }
                        end
                        ctx.push("nested_menu", {
                            title = _lc("Arrange"),
                            items_func = function()
                                return {
                                    {
                                        text = "Items List",
                                        sui_build = function(ctx2)
                                            local SUIWindow2 = require("engines/sui_window")
                                            local function save_order(items_to_save)
                                                local new_list = {}
                                                for _, it in ipairs(items_to_save) do
                                                    new_list[#new_list + 1] = it.orig_item
                                                end
                                                local RC2 = getRC()
                                                if RC2 and RC2.coll[name] then
                                                    local ordered = {}
                                                    for _, fp in ipairs(new_list) do
                                                        local entry = RC2.coll[name][fp]
                                                        if entry then ordered[#ordered + 1] = entry end
                                                    end
                                                    RC2:updateCollectionOrder(name, ordered)
                                                    RC2:write({ [name] = true })
                                                end
                                            end
                                            local cards = {}
                                            for i, item in ipairs(sort_items) do
                                                local _i  = i
                                                local _fp = item.orig_item
                                                cards[#cards + 1] = SUIWindow2.ArrangeCard{
                                                    inner_w   = ctx2.inner_w,
                                                    title     = item.text,
                                                    on_delete = function()
                                                        table.remove(sort_items, _i)
                                                        local RC3 = getRC()
                                                        if RC3 then RC3:removeItem(_fp, name) end
                                                        ctx_menu.refresh()
                                                        ctx2.repaint()
                                                    end,
                                                    on_move_up = (_i > 1) and function()
                                                        sort_items[_i], sort_items[_i-1] = sort_items[_i-1], sort_items[_i]
                                                        save_order(sort_items)
                                                        ctx_menu.refresh()
                                                        ctx2.repaint()
                                                    end or nil,
                                                    on_move_down = (_i < #sort_items) and function()
                                                        sort_items[_i], sort_items[_i+1] = sort_items[_i+1], sort_items[_i]
                                                        save_order(sort_items)
                                                        ctx_menu.refresh()
                                                        ctx2.repaint()
                                                    end or nil,
                                                }
                                            end
                                            if #cards == 0 then
                                                cards[#cards + 1] = SUIWindow2.ListRow{
                                                    title   = _lc("No books in this collection."),
                                                    inner_w = ctx2.inner_w,
                                                }
                                            end
                                            return cards
                                        end,
                                    },
                                }
                            end,
                        })
                    end,
                }
            end or nil,
        }

        return items
    end

    local mod = GridRenderer.makeModule{
        id          = inst_id,
        name        = _("Featured Collection"),
        default_on  = false,
        is_book_mod = true,   -- needed for the surgical repaint of the swipe
        max_items   = MAX_ITEMS,
        paged       = true,
        label_fn    = displayName,
        getFileList = function(ctx) return getFileList(ctx.pfx) end,
        extra_menu_items_before = extraMenuItemsBefore,

        -- Library-style corner badges (see engines/sui_book_grid.lua's
        -- GridRenderer.applyBadges) — same defaults as Flat Library: all
        -- three off, user-editable, nothing pre-enabled.
        badges = { pages = "off", series = "off", new = "off" },
        -- No toggles spec previously = default off, user-editable. Same
        -- intent expressed directly now (see GridRenderer.getProgressStyle).
        progress_style = { default = "none" },

        -- Opt-in grid (up to 3 rows x 4-5 columns, configurable in "Rows"/
        -- "Columns" in the module's menu). Default 1x5 replicates the previous
        -- behaviour byte-for-byte — it only changes when the user raises "Rows".
        grid          = true,
        default_rows  = 1,
        default_cols  = MAX_ITEMS,
    }

    -- "Not configured yet" notice, just like module_collections.lua when
    -- no collection is selected: without this, a Featured Collection that still has
    -- no collection chosen reserves the space (getHeight doesn't depend on the
    -- list) but paints nothing — a blank area with no explanation.
    local orig_build = mod.build
    function mod.build(w, ctx)
        local widget = orig_build(w, ctx)
        if widget then return widget end
        if getCollName(ctx.pfx) then return nil end -- collection chosen but empty: keeps the old behaviour

        local hold_on = SUISettings:nilOrTrue("simpleui_hs_settings_on_hold")
        local ph_text = hold_on and _("No collection selected  —  long press to configure")
                                 or _("No collection selected")
        return CenterContainer:new{
            dimen = Geom:new{ w = w, h = mod.getHeight(ctx) },
            UI.makeColoredText{
                text    = ph_text,
                face    = Font:getFace(SUIStyle.FACE_REGULAR, SUIStyle.FS_BODY),
                width   = w - PAD * 2,
            },
        }
    end

    return mod
end

-- ---------------------------------------------------------------------------
-- Export
-- ---------------------------------------------------------------------------
local M = {}
M.id            = "coll_row"
M.name          = _("Featured Collection")
M.instanciable  = true
M.instances_key = "simpleui_coll_row_instances"
M.makeInstance  = makeInstance

return M
