--- Tokens library catalogue: chip definitions, regular tokens, and
--- conditional templates. Data-only — projection (chip filtering, search)
--- and rendering live in menu/tokens_library.lua.
---
--- Edit by hand or via the curator web app at tools/curate_catalogues.py.
--- The curator overwrites this whole file on save, so any structural
--- changes (new tables, helpers) belong in menu/tokens_library.lua.
---
--- Entry shapes:
---   TOKENS:       { description, token, chip, [is_snippet] }
---   CONDITIONALS: { description, expression, chip }
--- The chip field tags which chip-strip filter shows the entry. "all"
--- merges TOKENS + CONDITIONALS for the All view.

local _ = require("bookends_i18n").gettext

local M = {}

M.CHIPS = {
    { key = "all", label = _("All") },
    { key = "book", label = _("Book") },
    { key = "progress", label = _("Progress") },
    { key = "time", label = _("Time") },
    { key = "session", label = _("Session") },
    { key = "device", label = _("Device") },
    { key = "ifelse", label = _("If/else") },
    { key = "templates", label = _("Templates") },
}

M.TOKENS = {
    { description = _("Document title"), token = "%title", chip = "book" },
    { description = _("First author"), token = "%author", chip = "book" },
    { description = _("All authors"), token = "%authors", chip = "book" },
    { description = _("Second author (empty if none)"), token = "%author_2", chip = "book" },
    { description = _("Series with index (combined)"), token = "%series", chip = "book" },
    { description = _("Series name only"), token = "%series_name", chip = "book" },
    { description = _("Series number only"), token = "%series_num", chip = "book" },
    { description = _("Chapter title (deepest)"), token = "%chap_title", chip = "book" },
    { description = _("Chapter title at depth 1"), token = "%chap_title_1", chip = "book" },
    { description = _("Chapter title at depth 2"), token = "%chap_title_2", chip = "book" },
    { description = _("Chapter title at depth 3"), token = "%chap_title_3", chip = "book" },
    { description = _("Chapter title without leading number (when detected)"), token = "%chap_title_name", chip = "book" },
    { description = _("Number from chapter title (when detected)"), token = "%chap_title_num", chip = "book" },
    { description = _("Current chapter number"), token = "%chap_num", chip = "book" },
    { description = _("Chapter count"), token = "%chap_count", chip = "book" },
    { description = _("File name"), token = "%filename", chip = "book" },
    { description = _("File position in folder"), token = "%file_num", chip = "book" },
    { description = _("Document files in folder"), token = "%file_count", chip = "book" },
    { description = _("Number of authors"), token = "%author_count", chip = "book" },
    { description = _("Short author list ('A, B, et al.' for 3+)"), token = "%authors_short", chip = "book" },
    { description = _("Reading status value (unread/reading/on_hold/finished)"), token = "%status", chip = "book" },
    { description = _("Reading status as a word"), token = "%status_label", chip = "book" },
    { description = _("Your rating as stars"), token = "%rating", chip = "book" },
    { description = _("Your rating as a number"), token = "%rating_number", chip = "book" },
    { description = _("Book description / blurb"), token = "%description", chip = "book" },
    { description = _("File size"), token = "%size", chip = "book" },
    { description = _("Date added (file date)"), token = "%added", chip = "book" },
    { description = _("Date last opened"), token = "%opened", chip = "book" },
    { description = _("Star glyph when the book is a favourite"), token = "%favourite", chip = "book" },
    { description = _("A highlight from this book"), token = "%quote", chip = "book" },
    { description = _("Title and author for the quote"), token = "%quote_source", chip = "book" },
    { description = _("Book language"), token = "%lang", chip = "book" },
    { description = _("Document format (EPUB, PDF, etc.)"), token = "%format", chip = "book" },
    { description = _("Calibre column by name, e.g. %calibre{mood}"), token = "%calibre{}", chip = "book", is_snippet = true },
    { description = _("Highlights count"), token = "%highlights", chip = "book" },
    { description = _("Notes count"), token = "%notes", chip = "book" },
    { description = _("Bookmarks count"), token = "%bookmarks", chip = "book" },
    { description = _("Annotations count (bookmarks + highlights + notes)"), token = "%annotations", chip = "book" },
    { description = _("Current page number"), token = "%page_num", chip = "progress" },
    { description = _("Total pages"), token = "%page_count", chip = "progress" },
    { description = _("Book percentage read"), token = "%book_pct", chip = "progress" },
    { description = _("Book % with 1 decimal (e.g. 45.3%)"), token = "%book_pct{1}", chip = "progress" },
    { description = _("Book % with 2 decimal places"), token = "%book_pct{2}", chip = "progress" },
    { description = _("Book % with 3 decimal places"), token = "%book_pct{3}", chip = "progress" },
    { description = _("Book % with 4 decimal places"), token = "%book_pct{4}", chip = "progress" },
    { description = _("Book percentage left"), token = "%book_pct_left", chip = "progress" },
    { description = _("Book % left with 1 decimal"), token = "%book_pct_left{1}", chip = "progress" },
    { description = _("Book % left with 2 decimals"), token = "%book_pct_left{2}", chip = "progress" },
    { description = _("Book % left with 3 decimals"), token = "%book_pct_left{3}", chip = "progress" },
    { description = _("Book % left with 4 decimals"), token = "%book_pct_left{4}", chip = "progress" },
    { description = _("Chapter percentage read"), token = "%chap_pct", chip = "progress" },
    { description = _("Chapter percentage left"), token = "%chap_pct_left", chip = "progress" },
    { description = _("Pages read in chapter"), token = "%chap_read", chip = "progress" },
    { description = _("Total pages in chapter"), token = "%chap_pages", chip = "progress" },
    { description = _("Pages left in chapter"), token = "%chap_pages_left", chip = "progress" },
    { description = _("Pages left in book"), token = "%pages_left", chip = "progress" },
    { description = _("Elastic gap: pushes the rest of the line to the far edge"), token = "%spacer", chip = "progress" },
    { description = _("Progress bar (configure type in line editor)"), token = "%bar", chip = "progress" },
    { description = _("Fixed-width progress bar (100px)"), token = "%bar{100}", chip = "progress" },
    { description = _("Progress bar, 10px tall"), token = "%bar{v10}", chip = "progress" },
    { description = _("Progress bar, 200px wide and 4px tall"), token = "%bar{200v4}", chip = "progress" },
    { description = _("Current time (24h, same as %time_24h)"), token = "%time", chip = "time" },
    { description = _("12-hour clock"), token = "%time_12h", chip = "time" },
    { description = _("24-hour clock"), token = "%time_24h", chip = "time" },
    { description = _("Date short (28 Mar)"), token = "%date", chip = "time" },
    { description = _("Date long (28 March 2026)"), token = "%date_long", chip = "time" },
    { description = _("Date numeric (28/03/2026)"), token = "%date_numeric", chip = "time" },
    { description = _("Weekday (Friday)"), token = "%weekday", chip = "time" },
    { description = _("Weekday short (Fri)"), token = "%weekday_short", chip = "time" },
    { description = _("Custom date/time format (strftime spec)"), token = "%datetime{%d %B}", chip = "time" },
    { description = _("Time left in chapter"), token = "%chap_time_left", chip = "time" },
    { description = _("Time left in book"), token = "%book_time_left", chip = "time" },
    { description = _("Time left in chapter (hours only)"), token = "%chap_time_left_h", chip = "time" },
    { description = _("Time left in chapter (minutes only)"), token = "%chap_time_left_m", chip = "time" },
    { description = _("Time left in book (hours only)"), token = "%book_time_left_h", chip = "time" },
    { description = _("Time left in book (minutes only)"), token = "%book_time_left_m", chip = "time" },
    { description = _("Chapter finish time (clock)"), token = "%chap_time_left_eta", chip = "time" },
    { description = _("Book finish time (clock)"), token = "%book_time_left_eta", chip = "time" },
    { description = _("Chapter finish time (custom format)"), token = "%chap_time_left_eta{%H:%M}", chip = "time" },
    { description = _("Book finish date (projected)"), token = "%book_finish_date", chip = "time" },
    { description = _("Book finish date (custom format)"), token = "%book_finish_date{%d %B %Y}", chip = "time" },
    { description = _("Session reading time"), token = "%session_time", chip = "session" },
    { description = _("Session pages read"), token = "%session_pages", chip = "session" },
    { description = _("Pages read today (all books)"), token = "%pages_today", chip = "session" },
    { description = _("Reading time today (all books)"), token = "%time_today", chip = "session" },
    { description = _("Pages read today (current book)"), token = "%pages_today_book", chip = "session" },
    { description = _("Reading time today (current book)"), token = "%time_today_book", chip = "session" },
    { description = _("Pages read in last 7 days (current book)"), token = "%pages_week_book", chip = "session" },
    { description = _("Reading time in last 7 days (current book)"), token = "%time_week_book", chip = "session" },
    { description = _("Day streak (any book)"), token = "%streak", chip = "session" },
    { description = _("Day streak (current book)"), token = "%book_streak", chip = "session" },
    { description = _("Lifetime reading time (all books)"), token = "%total_read_time", chip = "session" },
    { description = _("Books finished (lifetime)"), token = "%books_finished", chip = "session" },
    { description = _("Reading speed (pages/hour)"), token = "%speed", chip = "session" },
    { description = _("Average time per page"), token = "%avg_page_time", chip = "session" },
    { description = _("Total reading time for book"), token = "%book_read_time", chip = "session" },
    { description = _("Pages read of this book (lifetime)"), token = "%book_pages_read", chip = "session" },
    { description = _("Book read percentage (skip-aware)"), token = "%book_pct_read", chip = "session" },
    { description = _("Days reading this book"), token = "%days_reading_book", chip = "session" },
    { description = _("Pages per day for this book"), token = "%pages_per_day", chip = "session" },
    { description = _("Battery level"), token = "%batt", chip = "device" },
    { description = _("Wi-Fi icon (also answers to %wifi_icon)"), token = "%wifi", chip = "device" },
    { description = _("Wi-Fi icon, Bookshelf's name for it"), token = "%wifi_icon", chip = "device" },
    { description = _("Plugin content"), token = "%plugin_content", chip = "device" },
    { description = _("Frontlight brightness"), token = "%light", chip = "device" },
    { description = _("Frontlight brightness %"), token = "%light_pct", chip = "device" },
    { description = _("Frontlight warmth"), token = "%warmth", chip = "device" },
    { description = _("Frontlight warmth %"), token = "%warmth_pct", chip = "device" },
    { description = _("RAM used %"), token = "%mem", chip = "device" },
    { description = _("System memory used (MiB)"), token = "%sysused", chip = "device" },
    { description = _("RAM used (MiB)"), token = "%ram", chip = "device" },
    { description = _("Free disk space"), token = "%disk", chip = "device" },
    { description = _("Page X of Y, em-dash framed"), token = "\xE2\x80\x94 Page %page_num of %page_count \xE2\x80\x94", chip = "templates", is_snippet = true },
    { description = _("Title \xE2\x8B\xAE author (italic)"), token = "%title \xE2\x8B\xAE [i]%author[/i]", chip = "templates", is_snippet = true },
    { description = _("Title in a chosen font"), token = "[font=Noto Sans]%title[/font]", chip = "templates", is_snippet = true },
    { description = _("Bookmark(s) count + label"), token = "%bookmarks Bookmark(s)", chip = "templates", is_snippet = true },
    { description = _("Highlight(s) count + label"), token = "%highlights Highlight(s)", chip = "templates", is_snippet = true },
    { description = _("Hourglass session timer + pages"), token = "\xEE\xB0\x9E %session_time \xC2\xBB %session_pages page session", chip = "templates", is_snippet = true },
    { description = _("Sparkles 1"), token = "\xE2\x9C\xAE\xE2\x8B\x86\xCB\x9A\xEF\xBD\xA1\xE2\x8B\x86\xEF\xBD\xA1\xC2\xB0\xE2\x9C\xA9", chip = "templates" },
    { description = _("Sparkles 2"), token = "\xC2\xB0\xE2\x9D\x80\xE2\x8B\x86.\xE0\xB3\x83*:\xEF\xBD\xA5", chip = "templates" },
}

M.CONDITIONALS = {
    { description = _("If Wi-Fi is on"), expression = "[if:wifi=on]...[/if]", chip = "ifelse" },
    { description = _("If connected"), expression = "[if:connected=yes]...[/if]", chip = "ifelse" },
    { description = _("Battery 0\xE2\x80\x93100"), expression = "[if:batt<50]...[/if]", chip = "ifelse" },
    { description = _("If charging"), expression = "[if:charging=yes]...[/if]", chip = "ifelse" },
    { description = _("If page-turn flipped"), expression = "[if:invert=yes]...[/if]", chip = "ifelse" },
    { description = _("Book progress 0\xE2\x80\x93100"), expression = "[if:book_pct>50]...[/if]", chip = "ifelse" },
    { description = _("Chapter progress 0\xE2\x80\x93100"), expression = "[if:chap_pct>50]...[/if]", chip = "ifelse" },
    { description = _("Current chapter number"), expression = "[if:chap_num=1]...[/if]", chip = "ifelse" },
    { description = _("Total chapters"), expression = "[if:chap_count>20]...[/if]", chip = "ifelse" },
    { description = _("Minutes left in chapter"), expression = "[if:chap_time_left<10]...[/if]", chip = "ifelse" },
    { description = _("Whole hours left in chapter"), expression = "[if:chap_time_left_h>0]...[/if]", chip = "ifelse" },
    { description = _("Whole hours left in book"), expression = "[if:book_time_left_h>0]...[/if]", chip = "ifelse" },
    { description = _("Pages per hour"), expression = "[if:speed>0]...[/if]", chip = "ifelse" },
    { description = _("Minutes this session"), expression = "[if:session>30]...[/if]", chip = "ifelse" },
    { description = _("Pages this session"), expression = "[if:session_pages>0]...[/if]", chip = "ifelse" },
    { description = _("Pages read today"), expression = "[if:pages_today>0]...[/if]", chip = "ifelse" },
    { description = _("Pages today (current book)"), expression = "[if:pages_today_book>0]...[/if]", chip = "ifelse" },
    { description = _("Day streak (any book)"), expression = "[if:streak>=7]...[/if]", chip = "ifelse" },
    { description = _("Day streak (current book)"), expression = "[if:book_streak>=3]...[/if]", chip = "ifelse" },
    { description = _("Books finished"), expression = "[if:books_finished>=10]...[/if]", chip = "ifelse" },
    { description = _("Book read % (skip-aware)"), expression = "[if:book_pct_read>50]...[/if]", chip = "ifelse" },
    { description = _("odd / even"), expression = "[if:page=odd]...[/if]", chip = "ifelse" },
    { description = _("If frontlight on"), expression = "[if:light=on]...[/if]", chip = "ifelse" },
    { description = _("Frontlight brightness %"), expression = "[if:light_pct>50]...[/if]", chip = "ifelse" },
    { description = _("Frontlight warmth %"), expression = "[if:warmth_pct>50]...[/if]", chip = "ifelse" },
    { description = _("If night mode on"), expression = "[if:night=on]...[/if]", chip = "ifelse" },
    { description = _("EPUB / PDF / CBZ / \xE2\x80\xA6"), expression = "[if:format=EPUB]...[/if]", chip = "ifelse" },
    { description = _("Current HH:MM (24h)"), expression = "[if:time>18:00]...[/if]", chip = "ifelse" },
    { description = _("Mon\xE2\x80\x93Sun"), expression = "[if:day=Mon]...[/if]", chip = "ifelse" },
    { description = _("If book has title"), expression = "[if:title]...[/if]", chip = "ifelse" },
    { description = _("If book has author"), expression = "[if:author]...[/if]", chip = "ifelse" },
    { description = _("If book in series"), expression = "[if:series]...[/if]", chip = "ifelse" },
    { description = _("If chapter has title"), expression = "[if:chap_title]...[/if]", chip = "ifelse" },
    { description = _("Chapter title at depth 1/2/3"), expression = "[if:chap_title_2]...[/if]", chip = "ifelse" },
    { description = _("If book has 2+ authors"), expression = "[if:authors>1]...[/if]", chip = "ifelse" },
    { description = _("Author with et al. for multi-author"), expression = "[if:authors>1]%author, et al.[else]%author[/if]", chip = "templates" },
    { description = _("Wi-Fi icon only when Wi-Fi enabled"), expression = "[if:wifi=on]%wifi[/if]", chip = "templates" },
    { description = _("Low-battery warning"), expression = "[if:batt<20]LOW %batt_icon[/if]", chip = "templates" },
    { description = _("Bolt when charging"), expression = "[if:charging=yes]\xE2\x9A\xA1[/if] %batt_icon", chip = "templates" },
    { description = _("Arrow when page-turn flipped"), expression = "[if:invert=yes]\xE2\x87\x84[/if]", chip = "templates" },
    { description = _("Odd/even variations"), expression = "[if:page=odd]%page_num[else]%page_num[/if]", chip = "templates" },
    { description = _("Near end of book"), expression = "[if:book_pct>90]Almost done![/if]", chip = "templates" },
    { description = _("Frontlight on/off label"), expression = "[if:light=off]Light off[else]Light on[/if]", chip = "templates" },
    { description = _("If format"), expression = "[if:format!=PDF]%page_num / %page_count[/if]", chip = "templates" },
    { description = _("Weekends"), expression = "[if:day=Sat or day=Sun]Weekend![/if]", chip = "templates" },
    { description = _("Time window"), expression = "[if:time>=00:00 and time<5:00]Late night reading![/if]", chip = "templates" },
    { description = _("Non-series books"), expression = "[if:series]Series #%series_num[else]Standalone[/if]", chip = "templates" },
    { description = _("Fall back to shallower chapter"), expression = "[if:chap_title_2]%chap_title_2[else]%chap_title_1[/if]", chip = "templates" },
    { description = _("Chapter number then title"), expression = "[if:chap_title_num][b]%chap_title_num[/b] / %chap_title_name[else]%chap_title[/if]", chip = "templates" },
    { description = _("Long books (20+ chapters)"), expression = "[if:chap_count>20]Long read[/if]", chip = "templates" },
    -- Kindle's own wording for the same estimate: the hour segment disappears
    -- under an hour, and hr/min pluralise via the (s) pass. The space sits
    -- INSIDE the block so nothing is left behind when it collapses.
    { description = _("Time left in chapter, Kindle style"), expression = "[if:chap_time_left_h>0]%chap_time_left_h hr(s) [/if]%chap_time_left_m min(s) left in chapter", chip = "templates" },
    { description = _("Time left in book, Kindle style"), expression = "[if:book_time_left_h>0]%book_time_left_h hr(s) [/if]%book_time_left_m min(s) left in book", chip = "templates" },
    { description = _("Chapter title only when different from book title"), expression = "%title[if:chap_title_1!=@title] \xE2\x80\xA2 %chap_title_1[/if]", chip = "templates" },
    { description = _("Battery bars"), expression = "[if:batt>=0]\xE2\x96\xB0[else]\xE2\x96\xB1[/if][if:batt>=25]\xE2\x96\xB0[else]\xE2\x96\xB1[/if][if:batt>=50]\xE2\x96\xB0[else]\xE2\x96\xB1[/if][if:batt>=75]\xE2\x96\xB0[else]\xE2\x96\xB1[/if]", chip = "templates" },
}

return M
