-- localsend_i18n.lua — LocalSend plugin
-- Translation loader.
--
-- DESIGN (isolated proxy, no global monkey-patch)
-- =================================================
-- KOReader's bundled gettext is single-textdomain and only knows about the
-- strings compiled into the core koreader.pot/koreader.mo. A third-party,
-- OTA-distributed plugin like LocalSend cannot get its strings into that core
-- catalogue, so we ship our own flat locale/<lang>.po files and parse them
-- here.
--
-- The loader never touches package.loaded["gettext"] and never mutates the
-- global GetText module's fields. Replacing/wrapping the global module breaks
-- other plugins that load their own .po files (writes land on the wrapper and
-- never reach the native module). Instead we export a self-contained
-- translate() / ngettext() pair that main.lua assigns to its local `_` / `N_`
-- and injects into the submodules via the existing deps table — so the
-- submodules need no changes at all.
--
-- Strings not found in LocalSend's .po files fall through to the native
-- KOReader gettext, so shared UI words (that happen to exist in both) still
-- translate correctly.
--
-- Public API:
--   local I18n = require("localsend_i18n")
--   local _    = I18n.translate   -- replaces: local _ = require("gettext")
--   local N_   = I18n.ngettext    -- replaces: local N_ = _.ngettext
--   I18n.getLang()                -- current detected language
--   I18n.reset()                  -- clears cached translations (lang change)
--
-- HOW TO ADD A LANGUAGE
--   1. Copy locale/localsend.pot -> locale/<lang>.po  (e.g. locale/pt_PT.po)
--   2. Fill in the msgstr values.
--   3. Done — no code changes needed.

local logger = require("logger")

-- Locate the plugin directory from this file's own path. On-device the plugin
-- layout is flat (_meta.lua, main.lua, localsend_i18n.lua, locale/, ...) so the
-- directory holding this module is the plugin root and locale/ sits beside it.
local _dir = (debug.getinfo(1, "S").source:match("^@(.+/)") or "./")

-- ---------------------------------------------------------------------------
-- .po parser — minimal, handles the subset generated by locale/localsend.pot.
-- Supports msgid / msgid_plural / msgstr[N], multiline continuations, escape
-- sequences, and the Plural-Forms header.
-- ---------------------------------------------------------------------------
-- Parse gettext's small C-like plural-expression language instead of passing
-- catalogue content to loadstring(). Besides avoiding arbitrary Lua execution,
-- this handles numeric rules (plural=0) and nested ternaries consistently.
local function compilePluralForm(plural_forms)
    if type(plural_forms) ~= "string" then
        return nil
    end

    local nplurals = tonumber(plural_forms:match("nplurals%s*=%s*(%d+)%s*;"))
    local expr = plural_forms:match("plural%s*=%s*(.-)%s*;")
    if not nplurals or nplurals < 1 or not expr or expr == "" then
        return nil
    end

    local tokens = {}
    local i = 1
    while i <= #expr do
        local c = expr:sub(i, i)
        if c:match("%s") then
            i = i + 1
        elseif c:match("%d") then
            local value = expr:match("^%d+", i)
            table.insert(tokens, { kind = "number", value = tonumber(value) })
            i = i + #value
        elseif c == "n" then
            table.insert(tokens, { kind = "name", value = c })
            i = i + 1
        else
            local two = expr:sub(i, i + 1)
            if two == "||" or two == "&&" or two == "==" or two == "!=" or two == "<=" or two == ">=" then
                table.insert(tokens, { kind = "operator", value = two })
                i = i + 2
            elseif c:match("[?:()!<>+*/%%-]") then
                table.insert(tokens, { kind = "operator", value = c })
                i = i + 1
            else
                return nil
            end
        end
        if #tokens > 256 then
            return nil
        end
    end
    table.insert(tokens, { kind = "eof", value = "" })

    local pos = 1
    local parseConditional
    local function current(value)
        local token = tokens[pos]
        return token and (value == nil or token.value == value) and token or nil
    end
    local function accept(value)
        local token = current(value)
        if token then
            pos = pos + 1
        end
        return token
    end
    local function truthy(value)
        if type(value) == "number" then
            return value ~= 0
        end
        return value == true
    end
    local function boolNumber(value)
        return value and 1 or 0
    end
    local function binary(operator, left, right)
        if operator == "||" then
            return function(n)
                if truthy(left(n)) then
                    return 1
                end
                return boolNumber(truthy(right(n)))
            end
        elseif operator == "&&" then
            return function(n)
                if not truthy(left(n)) then
                    return 0
                end
                return boolNumber(truthy(right(n)))
            end
        elseif operator == "==" then
            return function(n)
                return boolNumber(left(n) == right(n))
            end
        elseif operator == "!=" then
            return function(n)
                return boolNumber(left(n) ~= right(n))
            end
        elseif operator == "<" then
            return function(n)
                return boolNumber(left(n) < right(n))
            end
        elseif operator == "<=" then
            return function(n)
                return boolNumber(left(n) <= right(n))
            end
        elseif operator == ">" then
            return function(n)
                return boolNumber(left(n) > right(n))
            end
        elseif operator == ">=" then
            return function(n)
                return boolNumber(left(n) >= right(n))
            end
        elseif operator == "+" then
            return function(n)
                return left(n) + right(n)
            end
        elseif operator == "-" then
            return function(n)
                return left(n) - right(n)
            end
        elseif operator == "*" then
            return function(n)
                return left(n) * right(n)
            end
        elseif operator == "/" then
            return function(n)
                local divisor = right(n)
                if divisor == 0 then
                    return 0 / 0
                end
                local quotient = left(n) / divisor
                return quotient < 0 and math.ceil(quotient) or math.floor(quotient)
            end
        elseif operator == "%" then
            return function(n)
                return left(n) % right(n)
            end
        end
    end

    local function parsePrimary()
        local token = current()
        if token.kind == "number" then
            pos = pos + 1
            local value = token.value
            return function()
                return value
            end
        elseif token.kind == "name" then
            pos = pos + 1
            return function(n)
                return n
            end
        elseif accept("(") then
            local nested = parseConditional()
            if not nested or not accept(")") then
                return nil
            end
            return nested
        end
        return nil
    end

    local function parseUnary()
        if accept("!") then
            local operand = parseUnary()
            return operand and function(n)
                return boolNumber(not truthy(operand(n)))
            end or nil
        elseif accept("+") then
            return parseUnary()
        elseif accept("-") then
            local operand = parseUnary()
            return operand and function(n)
                return -operand(n)
            end or nil
        end
        return parsePrimary()
    end

    local function parseBinary(nextParser, operators)
        local left = nextParser()
        if not left then
            return nil
        end
        while operators[current().value] do
            local operator = current().value
            pos = pos + 1
            local right = nextParser()
            if not right then
                return nil
            end
            left = binary(operator, left, right)
        end
        return left
    end

    local function parseMultiplicative()
        return parseBinary(parseUnary, { ["*"] = true, ["/"] = true, ["%"] = true })
    end
    local function parseAdditive()
        return parseBinary(parseMultiplicative, { ["+"] = true, ["-"] = true })
    end
    local function parseRelational()
        return parseBinary(parseAdditive, { ["<"] = true, ["<="] = true, [">"] = true, [">="] = true })
    end
    local function parseEquality()
        return parseBinary(parseRelational, { ["=="] = true, ["!="] = true })
    end
    local function parseAnd()
        return parseBinary(parseEquality, { ["&&"] = true })
    end
    local function parseOr()
        return parseBinary(parseAnd, { ["||"] = true })
    end

    parseConditional = function()
        local condition = parseOr()
        if not condition then
            return nil
        end
        if not accept("?") then
            return condition
        end
        local when_true = parseConditional()
        if not when_true or not accept(":") then
            return nil
        end
        local when_false = parseConditional()
        if not when_false then
            return nil
        end
        return function(n)
            return truthy(condition(n)) and when_true(n) or when_false(n)
        end
    end

    local evaluator = parseConditional()
    if not evaluator or current().kind ~= "eof" then
        return nil
    end

    return function(n)
        if type(n) ~= "number" then
            return nil
        end
        local ok, result = pcall(evaluator, n)
        if not ok or type(result) ~= "number" or result ~= result or result < 0 or result >= nplurals then
            return nil
        end
        return math.floor(result)
    end
end

local function parsePO(path)
    local f = io.open(path, "r")
    if not f then
        return nil
    end

    local map = {}
    local pluralizer = nil
    local entry = { msgid = nil, msgid_plural = nil, msgstrs = {}, fuzzy = false }
    local current_field = nil
    local pending_fuzzy = false

    local function flush()
        if not entry.msgid then
            entry = { msgid = nil, msgid_plural = nil, msgstrs = {}, fuzzy = false }
            current_field = nil
            return
        end

        if entry.msgid == "" then
            -- The empty-msgid entry holds the file header. Pull Plural-Forms
            -- out of it so ngettext() can pick the right form per language.
            local header = entry.msgstrs[0] or ""
            for line in header:gmatch("([^\n]*)\n?") do
                local plural_line = line:match("^Plural%-Forms:%s*(.-)%s*$")
                if plural_line then
                    pluralizer = compilePluralForm(plural_line)
                    break
                end
            end
        elseif not entry.fuzzy then
            if entry.msgid_plural then
                local trans = {}
                for idx, str in pairs(entry.msgstrs) do
                    if str and str ~= "" then
                        trans[idx] = str
                    end
                end
                if next(trans) then
                    map[entry.msgid] = trans
                end
            else
                local str = entry.msgstrs[0]
                if str and str ~= "" then
                    map[entry.msgid] = str
                end
            end
        end

        entry = { msgid = nil, msgid_plural = nil, msgstrs = {}, fuzzy = false }
        current_field = nil
    end

    local function unescape(s)
        local escapes = {
            a = "\a",
            b = "\b",
            f = "\f",
            n = "\n",
            r = "\r",
            t = "\t",
            v = "\v",
            ["\\"] = "\\",
            ['"'] = '"',
        }
        local result = {}
        local pos = 1
        while pos <= #s do
            local slash = s:find("\\", pos, true)
            if not slash then
                table.insert(result, s:sub(pos))
                break
            end
            table.insert(result, s:sub(pos, slash - 1))
            local escaped = s:sub(slash + 1, slash + 1)
            if escaped == "" then
                table.insert(result, "\\")
                break
            elseif escaped:match("[0-7]") then
                local digits = s:match("^[0-7][0-7]?[0-7]?", slash + 1)
                table.insert(result, string.char(tonumber(digits, 8)))
                pos = slash + 1 + #digits
            elseif escaped == "x" then
                local digits = s:match("^[0-9a-fA-F]+", slash + 2)
                if digits then
                    table.insert(result, string.char(tonumber(digits, 16) % 256))
                    pos = slash + 2 + #digits
                else
                    table.insert(result, "x")
                    pos = slash + 2
                end
            else
                table.insert(result, escapes[escaped] or escaped)
                pos = slash + 2
            end
        end
        return table.concat(result)
    end

    for line in f:lines() do
        local text = line:match("^%s*(.-)%s*$")
        if text == "" then
            flush()
            pending_fuzzy = false
        elseif text:match("^#,") then
            if text:match("[, ]fuzzy[, ]") or text:match("[, ]fuzzy$") then
                pending_fuzzy = true
            end
        -- Other comment lines match none of the branches below and are skipped.
        elseif text:match('^msgid%s+"') then
            flush()
            entry.msgid = unescape(text:match('^msgid%s+"(.*)"') or "")
            entry.fuzzy = pending_fuzzy
            pending_fuzzy = false
            current_field = "msgid"
        elseif text:match('^msgid_plural%s+"') then
            entry.msgid_plural = unescape(text:match('^msgid_plural%s+"(.*)"') or "")
            current_field = "msgid_plural"
        elseif text:match('^msgstr%[%d+%]%s+"') then
            local idx = tonumber(text:match('^msgstr%[(%d+)%]%s+"'))
            entry.msgstrs[idx] = unescape(text:match('^msgstr%[%d+%]%s+"(.*)"') or "")
            current_field = "msgstr" .. idx
        elseif text:match('^msgstr%s+"') then
            entry.msgstrs[0] = unescape(text:match('^msgstr%s+"(.*)"') or "")
            current_field = "msgstr0"
        elseif text:match('^"') and current_field then
            local cont = unescape(text:match('^"(.*)"') or "")
            if current_field == "msgid" then
                entry.msgid = entry.msgid .. cont
            elseif current_field == "msgid_plural" then
                entry.msgid_plural = entry.msgid_plural .. cont
            else
                local idx = tonumber(current_field:match("^msgstr(%d+)$"))
                if idx then
                    entry.msgstrs[idx] = (entry.msgstrs[idx] or "") .. cont
                end
            end
        end
    end
    flush()
    f:close()
    return map, pluralizer
end

-- ---------------------------------------------------------------------------
-- Language detection.
-- G_reader_settings:readSetting("language") is the KOReader UI language the
-- user picked; fall back to the C locale env vars if unset (e.g. headless
-- tests).
-- ---------------------------------------------------------------------------
local function detectLang()
    local lang = G_reader_settings and G_reader_settings:readSetting("language")
    if type(lang) == "string" and lang ~= "" then
        return lang
    end
    local lc = os.getenv("LANGUAGE") or os.getenv("LC_ALL") or os.getenv("LC_MESSAGES") or os.getenv("LANG") or ""
    lang = lc:match("^([a-zA-Z_]+)")
    return lang or "en"
end

-- ---------------------------------------------------------------------------
-- Load translation table (lazy, cached).
-- Tries the full locale (pt_PT) then falls back to the language prefix (pt).
-- ---------------------------------------------------------------------------
local _translations = nil
local _loaded = false

local function loadTranslations()
    if _loaded then
        return _translations
    end
    _loaded = true

    local lang = detectLang()
    -- KOReader uses C (and occasionally en/en_US) for source English, while
    -- en_GB is a real translated locale and may have a plugin catalogue.
    if lang == "C" or lang == "POSIX" or lang == "en" or lang:match("^en_US[.@]") or lang == "en_US" then
        return nil
    end

    local function try(name)
        if not name:match("^[%w_@.%-]+$") then
            return nil
        end
        local path = _dir .. "locale/" .. name .. ".po"
        local entries, pluralizer = parsePO(path)
        if entries and next(entries) then
            local n = 0
            for _ in pairs(entries) do
                n = n + 1
            end
            logger.info("localsend i18n: loaded " .. path .. " — " .. n .. " strings")
            return { entries = entries, plural = pluralizer }
        end
    end

    _translations = try(lang)
        or (function()
            local prefix = lang:match("^([a-zA-Z]+)")
            if prefix and prefix ~= lang then
                return try(prefix)
            end
        end)()

    if not _translations then
        logger.info("localsend i18n: no catalogue for " .. lang .. "; using KOReader/English fallback")
    end
    return _translations
end

-- ---------------------------------------------------------------------------
-- Core translation functions.
--
-- main.lua does:
--   local I18n = require("localsend_i18n")
--   local _  = I18n.translate
--   local N_ = I18n.ngettext
-- and injects _ / N_ into every submodule via the deps table.
--
-- Strings absent from LocalSend's catalogue fall through to the native
-- KOReader gettext without writing to or wrapping package.loaded["gettext"].
-- ---------------------------------------------------------------------------

local function translate(msgid)
    local t = loadTranslations()
    if t then
        local entry = t.entries[msgid]
        if type(entry) == "string" then
            return entry
        elseif type(entry) == "table" then
            -- Plural entry used with plain translate(): return the singular form.
            return entry[0] or entry[1] or msgid
        end
    end
    -- Read-only access to native gettext — no writes, no state mutation.
    local ok, gt = pcall(require, "gettext")
    if ok and gt then
        return gt(msgid)
    end
    return msgid
end

local function ngettext(msgid, msgid_plural, n)
    local t = loadTranslations()
    if t then
        local entry = t.entries[msgid]
        if type(entry) == "table" then
            local idx
            if t.plural then
                idx = t.plural(n)
            end
            if idx == nil then
                idx = (n == 1) and 0 or 1
            end
            local translated = entry[idx]
            if translated then
                return translated
            end
        elseif type(entry) == "string" and n == 1 then
            return entry
        end
    end
    -- Fall through to native gettext.
    local ok, gt = pcall(require, "gettext")
    if ok and gt then
        if type(gt) == "table" and type(gt.ngettext) == "function" then
            return gt.ngettext(msgid, msgid_plural, n)
        end
        local fallback = (n == 1) and msgid or msgid_plural
        return gt(fallback)
    end
    return (n == 1) and msgid or msgid_plural
end

-- ---------------------------------------------------------------------------
-- reset() — clears cached translations. Call after the user changes the UI
-- language so the next translate() re-reads the right .po file.
-- ---------------------------------------------------------------------------
local function reset()
    _translations = nil
    _loaded = false
    logger.info("localsend i18n: translation cache cleared")
end

return {
    translate = translate,
    ngettext = ngettext,
    getLang = detectLang,
    reset = reset,
}
