-- ./settings/simpleui/sui_settings.lua
return {
    ["simpleui_bar_enabled"] = true,
    ["simpleui_bar_mode"] = "both",
    ["simpleui_bar_tabs"] = {
        [1] = "home",
        [2] = "sui_settings",
        [3] = "homescreen",
        [4] = "stats_calendar",
        [5] = "history",
        [6] = "power",
    },
    ["simpleui_browsemeta_enabled"] = true,
    ["simpleui_coll_excluded"] = {},
    ["simpleui_coll_row_instances"] = {
        [1] = "coll_row_bec1a2",
        [2] = "coll_row_c07722",
    },
    ["simpleui_cs_cs_c2b55a_action_list_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_clock_battery"] = false,
    ["simpleui_cs_cs_c2b55a_clock_date"] = false,
    ["simpleui_cs_cs_c2b55a_clock_enabled"] = true,
    ["simpleui_cs_cs_c2b55a_coll_row_bec1a2_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_coll_row_c07722_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_collections_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_coverdeck_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_currently_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_flat_library_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_heatmap_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_module_order"] = {
        [1] = "quote",
        [2] = "clock",
        [3] = "reading_goals",
        [4] = "reading_stats",
        [5] = "recent",
        [6] = "currently",
        [7] = "new_books",
        [8] = "tbr",
        [9] = "coverdeck",
        [10] = "collections",
        [11] = "flat_library",
        [12] = "heatmap",
        [13] = "quick_actions_row_000001",
        [14] = "quick_actions_row_000002",
        [15] = "quick_actions_row_000003",
        [16] = "action_list",
        [17] = "spacer_row_beb5ea",
        [18] = "coll_row_bec1a2",
        [19] = "quick_actions_row_bed142",
        [20] = "spacer_row_bf810a",
        [21] = "spacer_row_bfcf2a",
        [22] = "coll_row_c07722",
    },
    ["simpleui_cs_cs_c2b55a_new_books_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_quick_actions_row_000001_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_quick_actions_row_000002_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_quick_actions_row_000003_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_quick_actions_row_bed142_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_quote_enabled"] = true,
    ["simpleui_cs_cs_c2b55a_reading_goals_enabled"] = true,
    ["simpleui_cs_cs_c2b55a_reading_stats_enabled"] = true,
    ["simpleui_cs_cs_c2b55a_recent_enabled"] = true,
    ["simpleui_cs_cs_c2b55a_spacer_row_beb5ea_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_spacer_row_bf810a_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_spacer_row_bfcf2a_enabled"] = false,
    ["simpleui_cs_cs_c2b55a_tbr_enabled"] = false,
    ["simpleui_custom_screens"] = {
        [1] = {
            ["id"] = "cs_c2b55a",
            ["layout_key"] = "simpleui_layout_cs_cs_c2b55a",
            ["name"] = "temp",
            ["pfx"] = "simpleui_cs_cs_c2b55a_",
        },
    },
    ["simpleui_enabled"] = true,
    ["simpleui_fc_cover_mode"] = "2_3",
    ["simpleui_fc_enabled"] = true,
    ["simpleui_fc_folder_style"] = "auto",
    ["simpleui_fc_subfolder_cover"] = true,
    ["simpleui_hide_label_reading_goals"] = true,
    ["simpleui_home_key_opens_hs"] = true,
    ["simpleui_hs_action_list_enabled"] = false,
    ["simpleui_hs_active_preset"] = "builtin_dashboard",
    ["simpleui_hs_bento_width_clock"] = 40,
    ["simpleui_hs_bento_width_quote"] = 60,
    ["simpleui_hs_bento_width_reading_goals"] = 35,
    ["simpleui_hs_bento_width_reading_stats"] = 65,
    ["simpleui_hs_clock_align"] = "left",
    ["simpleui_hs_clock_battery"] = false,
    ["simpleui_hs_clock_date"] = false,
    ["simpleui_hs_clock_enabled"] = true,
    ["simpleui_hs_clock_scale"] = 70,
    ["simpleui_hs_coll_row_bec1a2_enabled"] = false,
    ["simpleui_hs_coll_row_c07722_enabled"] = false,
    ["simpleui_hs_collections_enabled"] = false,
    ["simpleui_hs_coverdeck_enabled"] = true,
    ["simpleui_hs_coverdeck_show_author"] = false,
    ["simpleui_hs_coverdeck_show_book_days"] = false,
    ["simpleui_hs_coverdeck_show_book_remaining"] = false,
    ["simpleui_hs_coverdeck_show_book_time"] = false,
    ["simpleui_hs_coverdeck_show_percent"] = true,
    ["simpleui_hs_coverdeck_show_progress"] = true,
    ["simpleui_hs_coverdeck_show_stats"] = true,
    ["simpleui_hs_coverdeck_show_title"] = true,
    ["simpleui_hs_currently_bar_style"] = "with_pct",
    ["simpleui_hs_currently_enabled"] = true,
    ["simpleui_hs_currently_show_author"] = true,
    ["simpleui_hs_currently_show_book_days"] = true,
    ["simpleui_hs_currently_show_book_remaining"] = true,
    ["simpleui_hs_currently_show_book_time"] = true,
    ["simpleui_hs_currently_show_description"] = true,
    ["simpleui_hs_currently_show_percent"] = false,
    ["simpleui_hs_currently_show_progress"] = true,
    ["simpleui_hs_currently_show_series"] = false,
    ["simpleui_hs_currently_show_title"] = true,
    ["simpleui_hs_currently_stats_style"] = "compact",
    ["simpleui_hs_flat_library_enabled"] = false,
    ["simpleui_hs_heatmap_enabled"] = false,
    ["simpleui_hs_module_order"] = {
        [1] = "clock",
        [2] = "quote",
        [3] = "currently",
        [4] = "reading_goals",
        [5] = "reading_stats",
        [6] = "recent",
        [7] = "coverdeck",
        [8] = "new_books",
        [9] = "tbr",
        [10] = "collections",
        [11] = "flat_library",
        [12] = "heatmap",
        [13] = "quick_actions_row_000001",
        [14] = "quick_actions_row_000002",
        [15] = "quick_actions_row_000003",
        [16] = "action_list",
        [17] = "spacer_row_beb5ea",
        [18] = "coll_row_bec1a2",
        [19] = "quick_actions_row_bed142",
        [20] = "spacer_row_bf810a",
        [21] = "spacer_row_bfcf2a",
        [22] = "coll_row_c07722",
    },
    ["simpleui_hs_new_books_enabled"] = false,
    ["simpleui_hs_quick_actions_row_000001_enabled"] = false,
    ["simpleui_hs_quick_actions_row_000002_enabled"] = false,
    ["simpleui_hs_quick_actions_row_000003_enabled"] = false,
    ["simpleui_hs_quick_actions_row_bed142_enabled"] = false,
    ["simpleui_hs_quote_enabled"] = true,
    ["simpleui_hs_quote_scale"] = 80,
    ["simpleui_hs_reading_goals_enabled"] = true,
    ["simpleui_hs_reading_goals_item_label_scale"] = 130,
    ["simpleui_hs_reading_goals_ring_content"] = "outside",
    ["simpleui_hs_reading_goals_scale"] = 90,
    ["simpleui_hs_reading_stats_enabled"] = true,
    ["simpleui_hs_reading_stats_items"] = {
        [1] = "today_time",
        [2] = "streak",
    },
    ["simpleui_hs_reading_stats_type"] = "list",
    ["simpleui_hs_recent_enabled"] = true,
    ["simpleui_hs_recent_show_finished"] = true,
    ["simpleui_hs_simpleui_quote_align"] = "right",
    ["simpleui_hs_spacer_row_beb5ea_enabled"] = false,
    ["simpleui_hs_spacer_row_bf810a_enabled"] = false,
    ["simpleui_hs_spacer_row_bfcf2a_enabled"] = false,
    ["simpleui_hs_tbr_enabled"] = false,
    ["simpleui_layout"] = {
        ["pages"] = {
            [1] = {
                ["id"] = 1,
                ["modules"] = {
                    [1] = "clock",
                    [2] = "quote",
                    [3] = "currently",
                    [4] = "reading_stats",
                },
            },
            [2] = {
                ["id"] = 1788899689,
                ["modules"] = {
                    [1] = "recent",
                    [2] = "coverdeck",
                },
            },
        },
    },
    ["simpleui_layout_cs_cs_c2b55a"] = {
        ["pages"] = {
            [1] = {
                ["id"] = 1,
                ["modules"] = {
                    [1] = "quote",
                    [2] = "clock",
                    [3] = "reading_goals",
                    [4] = "reading_stats",
                    [5] = "recent",
                },
            },
        },
    },
    ["simpleui_loaded_version"] = "2.7.1",
    ["simpleui_onboarding_done"] = true,
    ["simpleui_qa_list"] = {},
    ["simpleui_qa_migrated_v1"] = true,
    ["simpleui_qa_row_instances"] = {
        [1] = "quick_actions_row_000001",
        [2] = "quick_actions_row_000002",
        [3] = "quick_actions_row_000003",
        [4] = "quick_actions_row_bed142",
    },
    ["simpleui_qs_bar_bg"] = "flat",
    ["simpleui_qs_bar_enabled"] = true,
    ["simpleui_qs_bar_frontlight"] = false,
    ["simpleui_qs_bar_settings_on_hold"] = true,
    ["simpleui_qs_bar_shape"] = "round",
    ["simpleui_qs_bar_slots"] = {
        [1] = "wifi_toggle",
        [2] = "bookmark_browser",
        [3] = "frontlight",
        [4] = "night_mode",
        [5] = "power",
        [6] = "sui_settings",
    },
    ["simpleui_qs_bar_warmth"] = false,
    ["simpleui_quote_deck_count"] = 99,
    ["simpleui_quote_deck_order"] = "6,76,78,95,72,71,18,83,49,22,93,31,36,47,45,54,19,43,67,3,62,97,77,86,37,60,17,27,99,9,10,96,48,81,87,28,75,1,42,26,29,33,66,13,51,40,24,34,25,56,90,7,84,65,38,98,64,21,88,20,92,74,12,53,70,80,4,57,2,41,59,89,44,16,50,14,35,94,46,55,91,30,23,82,15,61,85,5,11,52,39,68,32,63,8,73,58,69,79",
    ["simpleui_quote_deck_pos"] = 63,
    ["simpleui_reading_goals_layout"] = "compact",
    ["simpleui_reading_goals_show_annual"] = true,
    ["simpleui_reading_goals_show_daily"] = true,
    ["simpleui_reading_goals_show_monthly"] = true,
    ["simpleui_settings_migrated_v2"] = true,
    ["simpleui_settings_migrated_v3"] = true,
    ["simpleui_settings_migrated_v4"] = true,
    ["simpleui_settings_migrated_v5"] = true,
    ["simpleui_settings_migrated_v6"] = true,
    ["simpleui_settings_migrated_v7"] = true,
    ["simpleui_settings_migrated_v8"] = true,
    ["simpleui_spacer_row_instances"] = {
        [1] = "spacer_row_beb5ea",
        [2] = "spacer_row_bf810a",
        [3] = "spacer_row_bfcf2a",
    },
    ["simpleui_stale_stats_v1"] = {
        ["avg_pages"] = 12,
        ["avg_secs"] = 921,
        ["books_total"] = 5,
        ["books_year"] = 5,
        ["db_conn_fatal"] = false,
        ["month_pages"] = 87,
        ["month_secs"] = 6573,
        ["streak"] = 5,
        ["today_pages"] = 6,
        ["today_secs"] = 288,
        ["total_secs"] = 279606,
        ["week_pages"] = 27,
        ["week_secs"] = 1935,
        ["year_secs"] = 226756,
    },
    ["simpleui_streak_freeze_last_total_secs"] = 279606,
    ["simpleui_streak_freeze_time_secs"] = 315,
    ["simpleui_streak_freeze_watermark"] = 5,
    ["simpleui_streak_freezes_available"] = 1,
    ["simpleui_style_wallpaper_enabled"] = true,
    ["simpleui_style_wallpaper_opacity"] = 0,
    ["simpleui_tb_fm_cfg"] = {
        ["order_left"] = {
            [1] = "fm_back",
            [2] = "fm_search",
        },
        ["order_right"] = {
            [1] = "fm_browse",
            [2] = "fm_menu",
        },
        ["side"] = {
            ["fm_back"] = "left",
            ["fm_browse"] = "right",
            ["fm_menu"] = "right",
            ["fm_search"] = "left",
        },
    },
    ["simpleui_tb_item_fm_browse"] = true,
    ["simpleui_tb_item_fm_search"] = true,
    ["simpleui_topbar_config"] = {
        ["order_left"] = {
            [1] = "clock",
        },
        ["order_right"] = {
            [1] = "wifi",
            [2] = "battery",
        },
        ["side"] = {
            ["battery"] = "right",
            ["clock"] = "left",
            ["wifi"] = "right",
        },
    },
    ["simpleui_topbar_enabled"] = true,
    ["simpleui_updater_auto_check"] = true,
}
