local DataStorage = require("datastorage")
local UIManager = require("ui/uimanager")
local InfoMessage = require("ui/widget/infomessage")
local FileManager = require("apps/filemanager/filemanager")
local _ = require("appstore_gettext")
local Net = require("appstore_net")
local util = require("util")
local logger = require("logger")
local lfs = require("libs/libkoreader-lfs")
local Version = require("version")
local Mirror = require("appstore_mirror")

local RepoContent = {}

-- TextViewer only gained Markdown rendering (text_format = "md") in KOReader
-- v2026.07. Older versions keep the cache-to-file-then-open flow below.
local README_POPUP_MIN_VERSION = Version:getNormalizedVersion("v2026.07")
function RepoContent.supportsReadmePopup()
    return (Version:getNormalizedCurrentVersion() or 0) >= README_POPUP_MIN_VERSION
end

local function getCacheDir()
    local dir = DataStorage:getDataDir() .. "/cache/appstore/readme"
    local ok, err = util.makePath(dir)
    if not ok then
        logger.warn("AppStore README cache dir failure", err)
    end
    return dir
end

local function buildRawUrl(owner, repo)
    return string.format("https://raw.githubusercontent.com/%s/%s/HEAD/README.md", owner, repo)
end

local function download(url)
    local response = {}
    -- This runs on the UI thread: a connection that never answers would otherwise hold the
    -- interface until KOReader is restarted.
    local code, _, status = Net.requestToTable({
        url = url,
        headers = {
            ["Accept"] = "text/plain",
            ["User-Agent"] = "KOReader-AppStore",
        },
    }, response)
    -- A timeout arrives as a string in place of a status; a throw leaves nothing there at
    -- all and its reason in `status`. Kept apart, so the caller can tell one from the other.
    return code, status, table.concat(response)
end

-- Download and clean the raw README body, shared by the cached and
-- direct-to-viewer fetch paths below.
local function downloadReadmeBody(owner, repo)
    if not owner or not repo then
        return nil, "missing owner/repo"
    end
    local url = Mirror.apply(buildRawUrl(owner, repo))
    local code, status, body = download(url)
    -- Same rule as fetchGitHubRaw: a throw has no code, and its reason is not HTTP.
    if tonumber(code) ~= 200 then
        if code then
            return nil, string.format("HTTP %s", tostring(code))
        end
        return nil, tostring(status or "network error")
    end
    if not body or body == "" then
        return nil, "empty body"
    end
    -- Strip inline HTML <img> tags to avoid rendering issues in the text viewer.
    -- This keeps the textual README content while dropping embedded images.
    body = body:gsub("<img[^>]->", "")
    return body
end

-- Legacy path (KOReader older than TextViewer markdown support): download the
-- README and cache it to disk, returning the file path.
function RepoContent.fetchReadme(owner, repo)
    local body, err = downloadReadmeBody(owner, repo)
    if not body then
        return false, err
    end
    local dir = getCacheDir()
    local safe_owner = owner:gsub("[^%w_-]", "_")
    local safe_repo = repo:gsub("[^%w_-]", "_")
    local path = string.format("%s/%s_%s_README.md", dir, safe_owner, safe_repo)
    local ok, werr = util.writeToFile(body, path)
    if not ok then
        return false, werr or "write error"
    end
    return true, path
end

-- Direct-to-viewer path: download the README and return its content, with no
-- on-disk caching.
function RepoContent.fetchReadmeContent(owner, repo)
    return downloadReadmeBody(owner, repo)
end

-- Remove every cached README markdown file generated by RepoContent.fetchReadme.
-- Returns a table with `removed` count and `errors` list (failed file paths).
function RepoContent.clearReadmeCache()
    local dir = DataStorage:getDataDir() .. "/cache/appstore/readme"
    local removed = 0
    local errors = {}
    if lfs.attributes(dir, "mode") ~= "directory" then
        return { removed = 0, errors = errors }
    end
    for entry in lfs.dir(dir) do
        if entry ~= "." and entry ~= ".." then
            local full_path = dir .. "/" .. entry
            local mode = lfs.attributes(full_path, "mode")
            if mode == "file" then
                local ok = os.remove(full_path)
                if ok then
                    removed = removed + 1
                else
                    table.insert(errors, full_path)
                end
            end
        end
    end
    return { removed = removed, errors = errors }
end

function RepoContent.openReadme(path)
    if not path then
        UIManager:show(InfoMessage:new{ text = _("Missing README path"), timeout = 4 })
        return
    end
    local text, err = util.readFromFile(path)
    if not text or text == "" then
        UIManager:show(InfoMessage:new{ text = _("Unable to read README file"), timeout = 4 })
        return
    end
    FileManager:openFile(path)
end

return RepoContent

