-- ./settings/bookends.lua
return {
    ["active_preset_filename"] = "basic_bookends.lua",
    ["bar_colors_promoted_to_per_bar"] = true,
    ["detached_state_recovery_done"] = true,
    ["dev_branch"] = "",
    ["font_face"] = "./fonts/noto/NotoSans-Regular.ttf",
    ["font_scale"] = 100,
    ["font_size"] = 14,
    ["last_install_source"] = "release",
    ["manual_active_preset_seeded"] = true,
    ["margin_bottom"] = 10,
    ["margin_left"] = 18,
    ["margin_right"] = 18,
    ["margin_top"] = 10,
    ["migrated"] = true,
    ["overlap_gap"] = 50,
    ["pos_bc"] = {
        ["line_font_size"] = {
            [1] = 14,
        },
        ["lines"] = {
            [1] = "Page %page_num of %page_count",
        },
    },
    ["pos_bl"] = {
        ["lines"] = {},
    },
    ["pos_br"] = {
        ["lines"] = {},
    },
    ["pos_tc"] = {
        ["line_font_size"] = {
            [1] = 14,
        },
        ["lines"] = {
            [1] = "%time_12h",
        },
    },
    ["pos_tl"] = {
        ["lines"] = {},
    },
    ["pos_tr"] = {
        ["lines"] = {},
    },
    ["preset_cycle"] = {
        [1] = "basic_bookends.lua",
    },
    ["preset_manager_migration_done"] = true,
    ["progress_bar_1"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = true,
        ["height"] = 5,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_2"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_3"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_4"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_5"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_6"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_7"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_8"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["schema_version"] = 5,
    ["skim_on_hold"] = true,
    ["truncation_priority"] = "center",
}
