-- ./settings/reading_insights_cache.lua
return {
    ["alltime_base"] = {
        ["data"] = {
            ["book_count"] = 89,
            ["duration"] = 279295,
            ["pages"] = 3332,
        },
        ["date"] = "2026-09-09",
    },
    ["completed_year"] = {},
    ["goal_finished_books"] = {
        ["2025"] = {
            ["2"] = 1765158297,
        },
        ["2026"] = {
            ["18"] = 1772422661,
            ["26"] = 1773624742,
            ["29"] = 1772506655,
            ["78"] = 1786093127,
            ["9"] = 1770616246,
            ["91"] = 1784289941,
            ["96"] = 1787615255,
            ["99"] = 1788823449,
        },
    },
    ["goal_scan_watermark"] = {
        ["2025"] = {
            ["rows"] = 4497,
            ["time"] = 1788981887,
        },
        ["2026"] = {
            ["rows"] = 4497,
            ["time"] = 1788981887,
        },
    },
    ["monthly_base"] = {
        ["hours:2026"] = {
            ["data"] = {
                ["2026-01"] = 7593,
                ["2026-02"] = 17583,
                ["2026-03"] = 25129,
                ["2026-04"] = 38684,
                ["2026-05"] = 12641,
                ["2026-06"] = 33180,
                ["2026-07"] = 53631,
                ["2026-08"] = 31719,
                ["2026-09"] = 6285,
            },
            ["date"] = "2026-09-09",
        },
    },
    ["stale_cache"] = {
        ["all_time"] = {
            ["book_count"] = 89,
            ["duration"] = 279632,
            ["hours"] = 77,
            ["pages"] = 3337,
        },
        ["last_week"] = {
            ["avg_pages"] = 12.285714285714,
            ["avg_seconds"] = 928.85714285714,
        },
        ["last_week_daily"] = {
            [1] = {
                ["hours"] = 0.1,
                ["label"] = "Today",
                ["midnight_ts"] = 1788901200,
                ["pages"] = 6,
                ["seconds"] = 337,
            },
            [2] = {
                ["hours"] = 0.3,
                ["label"] = "Yesterday",
                ["midnight_ts"] = 1788814800,
                ["pages"] = 13,
                ["seconds"] = 926,
            },
            [3] = {
                ["hours"] = 0.2,
                ["label"] = "Mon",
                ["midnight_ts"] = 1788728400,
                ["pages"] = 8,
                ["seconds"] = 721,
            },
            [4] = {
                ["hours"] = 0.1,
                ["label"] = "Sun",
                ["midnight_ts"] = 1788642000,
                ["pages"] = 2,
                ["seconds"] = 222,
            },
            [5] = {
                ["hours"] = 0.1,
                ["label"] = "Sat",
                ["midnight_ts"] = 1788555600,
                ["pages"] = 2,
                ["seconds"] = 213,
            },
            [6] = {
                ["hours"] = 0,
                ["label"] = "Fri",
                ["midnight_ts"] = 1788469200,
                ["pages"] = 0,
                ["seconds"] = 0,
            },
            [7] = {
                ["hours"] = 1,
                ["label"] = "Thu",
                ["midnight_ts"] = 1788382800,
                ["pages"] = 55,
                ["seconds"] = 4083,
            },
        },
        ["streaks"] = {
            ["_today_confirmed"] = true,
            ["best_days"] = 23,
            ["best_days_dates"] = {
                ["end_"] = "2026-07-09",
                ["start"] = "2026-06-17",
            },
            ["best_weeks"] = 34,
            ["best_weeks_dates"] = {
                ["end_"] = "2026-09-07",
                ["start"] = "2026-01-19",
            },
            ["current_days"] = 5,
            ["current_days_dates"] = {
                ["end_"] = "2026-09-09",
                ["start"] = "2026-09-05",
            },
            ["current_weeks"] = 34,
            ["current_weeks_dates"] = {
                ["end_"] = "2026-09-07",
                ["start"] = "2026-01-19",
            },
        },
        ["year_range"] = {
            ["max_year"] = 2026,
            ["min_month"] = 11,
            ["min_year"] = 2025,
        },
    },
    ["stale_monthly"] = {
        ["hours:2026:2026-09-09"] = {
            [1] = {
                ["hours"] = 2,
                ["label"] = "Jan",
                ["label_full"] = "January",
                ["month"] = "2026-01",
                ["seconds"] = 7593,
            },
            [2] = {
                ["hours"] = 4,
                ["label"] = "Feb",
                ["label_full"] = "February",
                ["month"] = "2026-02",
                ["seconds"] = 17583,
            },
            [3] = {
                ["hours"] = 6,
                ["label"] = "Mar",
                ["label_full"] = "March",
                ["month"] = "2026-03",
                ["seconds"] = 25129,
            },
            [4] = {
                ["hours"] = 10,
                ["label"] = "Apr",
                ["label_full"] = "April",
                ["month"] = "2026-04",
                ["seconds"] = 38684,
            },
            [5] = {
                ["hours"] = 3,
                ["label"] = "May",
                ["label_full"] = "May",
                ["month"] = "2026-05",
                ["seconds"] = 12641,
            },
            [6] = {
                ["hours"] = 9,
                ["label"] = "Jun",
                ["label_full"] = "June",
                ["month"] = "2026-06",
                ["seconds"] = 33180,
            },
            [7] = {
                ["hours"] = 14,
                ["label"] = "Jul",
                ["label_full"] = "July",
                ["month"] = "2026-07",
                ["seconds"] = 53631,
            },
            [8] = {
                ["hours"] = 8,
                ["label"] = "Aug",
                ["label_full"] = "August",
                ["month"] = "2026-08",
                ["seconds"] = 31719,
            },
            [9] = {
                ["hours"] = 1,
                ["label"] = "Sep",
                ["label_full"] = "September",
                ["month"] = "2026-09",
                ["seconds"] = 6622,
            },
            [10] = {
                ["hours"] = 0,
                ["label"] = "Oct",
                ["label_full"] = "October",
                ["month"] = "2026-10",
                ["seconds"] = 0,
            },
            [11] = {
                ["hours"] = 0,
                ["label"] = "Nov",
                ["label_full"] = "November",
                ["month"] = "2026-11",
                ["seconds"] = 0,
            },
            [12] = {
                ["hours"] = 0,
                ["label"] = "Dec",
                ["label_full"] = "December",
                ["month"] = "2026-12",
                ["seconds"] = 0,
            },
        },
    },
    ["stale_yearly"] = {
        ["2026:v3:2026-09-09"] = {
            ["avg_days_per_book"] = 2,
            ["books_started"] = 83,
            ["days"] = 166,
            ["duration"] = 226782,
            ["pages"] = 2997,
        },
    },
    ["yearly_base"] = {
        ["2026:v3"] = {
            ["data"] = {
                ["book_ids"] = {
                    ["100LL"] = true,
                    ["10LL"] = true,
                    ["11LL"] = true,
                    ["12LL"] = true,
                    ["13LL"] = true,
                    ["14LL"] = true,
                    ["15LL"] = true,
                    ["16LL"] = true,
                    ["17LL"] = true,
                    ["18LL"] = true,
                    ["19LL"] = true,
                    ["20LL"] = true,
                    ["22LL"] = true,
                    ["23LL"] = true,
                    ["24LL"] = true,
                    ["25LL"] = true,
                    ["26LL"] = true,
                    ["27LL"] = true,
                    ["28LL"] = true,
                    ["29LL"] = true,
                    ["30LL"] = true,
                    ["32LL"] = true,
                    ["33LL"] = true,
                    ["34LL"] = true,
                    ["35LL"] = true,
                    ["36LL"] = true,
                    ["37LL"] = true,
                    ["38LL"] = true,
                    ["39LL"] = true,
                    ["40LL"] = true,
                    ["41LL"] = true,
                    ["42LL"] = true,
                    ["43LL"] = true,
                    ["44LL"] = true,
                    ["45LL"] = true,
                    ["46LL"] = true,
                    ["47LL"] = true,
                    ["48LL"] = true,
                    ["49LL"] = true,
                    ["51LL"] = true,
                    ["55LL"] = true,
                    ["56LL"] = true,
                    ["57LL"] = true,
                    ["58LL"] = true,
                    ["59LL"] = true,
                    ["60LL"] = true,
                    ["61LL"] = true,
                    ["62LL"] = true,
                    ["63LL"] = true,
                    ["64LL"] = true,
                    ["65LL"] = true,
                    ["66LL"] = true,
                    ["68LL"] = true,
                    ["69LL"] = true,
                    ["70LL"] = true,
                    ["71LL"] = true,
                    ["72LL"] = true,
                    ["73LL"] = true,
                    ["74LL"] = true,
                    ["75LL"] = true,
                    ["76LL"] = true,
                    ["77LL"] = true,
                    ["78LL"] = true,
                    ["79LL"] = true,
                    ["7LL"] = true,
                    ["81LL"] = true,
                    ["84LL"] = true,
                    ["85LL"] = true,
                    ["86LL"] = true,
                    ["87LL"] = true,
                    ["88LL"] = true,
                    ["89LL"] = true,
                    ["8LL"] = true,
                    ["91LL"] = true,
                    ["92LL"] = true,
                    ["93LL"] = true,
                    ["94LL"] = true,
                    ["95LL"] = true,
                    ["96LL"] = true,
                    ["97LL"] = true,
                    ["98LL"] = true,
                    ["99LL"] = true,
                    ["9LL"] = true,
                },
                ["books_started"] = 83,
                ["days"] = 165,
                ["duration"] = 226445,
                ["pages"] = 2991,
            },
            ["date"] = "2026-09-09",
        },
    },
}
